// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAD9mEQdgd8ctYZJxzWhbaROPo_v3G9-IA',
    appId: '1:562579131929:web:a77ebf1702237a3775e488',
    messagingSenderId: '562579131929',
    projectId: 'flutterauth-ad73a',
    authDomain: 'flutterauth-ad73a.firebaseapp.com',
    storageBucket: 'flutterauth-ad73a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1u37MDzMlMLb30e4KfKdt-epE60r6KdQ',
    appId: '1:562579131929:android:c447e19128ea4c6975e488',
    messagingSenderId: '562579131929',
    projectId: 'flutterauth-ad73a',
    storageBucket: 'flutterauth-ad73a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNnrwD3LLEYyALNRm124-uASPoENX0ZpY',
    appId: '1:562579131929:ios:5d98e03251c19eff75e488',
    messagingSenderId: '562579131929',
    projectId: 'flutterauth-ad73a',
    storageBucket: 'flutterauth-ad73a.appspot.com',
    iosBundleId: 'com.example.onboardingScreen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNnrwD3LLEYyALNRm124-uASPoENX0ZpY',
    appId: '1:562579131929:ios:7a5421e4304ba32675e488',
    messagingSenderId: '562579131929',
    projectId: 'flutterauth-ad73a',
    storageBucket: 'flutterauth-ad73a.appspot.com',
    iosBundleId: 'com.example.onboardingScreen.RunnerTests',
  );
}
